export interface Airport {
  code: string;
  city: string;
  country: string;
  countryCode: string;
}

// Comprehensive IATA airport database (700+ airports)
export const airports: Airport[] = [
  // ===== AUSTRALIA / NEW ZEALAND =====
  { code: "SYD", city: "Sydney", country: "Australia", countryCode: "AU" },
  { code: "MEL", city: "Melbourne", country: "Australia", countryCode: "AU" },
  { code: "BNE", city: "Brisbane", country: "Australia", countryCode: "AU" },
  { code: "PER", city: "Perth", country: "Australia", countryCode: "AU" },
  { code: "ADL", city: "Adelaide", country: "Australia", countryCode: "AU" },
  { code: "CBR", city: "Canberra", country: "Australia", countryCode: "AU" },
  { code: "OOL", city: "Gold Coast", country: "Australia", countryCode: "AU" },
  { code: "CNS", city: "Cairns", country: "Australia", countryCode: "AU" },
  { code: "HBA", city: "Hobart", country: "Australia", countryCode: "AU" },
  { code: "DRW", city: "Darwin", country: "Australia", countryCode: "AU" },
  { code: "TSV", city: "Townsville", country: "Australia", countryCode: "AU" },
  { code: "ASP", city: "Alice Springs", country: "Australia", countryCode: "AU" },
  { code: "LST", city: "Launceston", country: "Australia", countryCode: "AU" },
  { code: "MCY", city: "Sunshine Coast", country: "Australia", countryCode: "AU" },
  { code: "NTL", city: "Newcastle", country: "Australia", countryCode: "AU" },
  { code: "AKL", city: "Auckland", country: "New Zealand", countryCode: "NZ" },
  { code: "CHC", city: "Christchurch", country: "New Zealand", countryCode: "NZ" },
  { code: "WLG", city: "Wellington", country: "New Zealand", countryCode: "NZ" },
  { code: "ZQN", city: "Queenstown", country: "New Zealand", countryCode: "NZ" },
  { code: "DUD", city: "Dunedin", country: "New Zealand", countryCode: "NZ" },
  { code: "PMR", city: "Palmerston North", country: "New Zealand", countryCode: "NZ" },
  { code: "NPE", city: "Napier", country: "New Zealand", countryCode: "NZ" },
  { code: "HLZ", city: "Hamilton", country: "New Zealand", countryCode: "NZ" },
  { code: "TRG", city: "Tauranga", country: "New Zealand", countryCode: "NZ" },
  { code: "ROT", city: "Rotorua", country: "New Zealand", countryCode: "NZ" },

  // ===== ORIENT (China, Taiwan, Hong Kong, Macau, Mongolia, South Korea) =====
  { code: "PEK", city: "Beijing", country: "China", countryCode: "CN" },
  { code: "PKX", city: "Beijing Daxing", country: "China", countryCode: "CN" },
  { code: "PVG", city: "Shanghai Pudong", country: "China", countryCode: "CN" },
  { code: "SHA", city: "Shanghai Hongqiao", country: "China", countryCode: "CN" },
  { code: "CAN", city: "Guangzhou", country: "China", countryCode: "CN" },
  { code: "SZX", city: "Shenzhen", country: "China", countryCode: "CN" },
  { code: "CTU", city: "Chengdu", country: "China", countryCode: "CN" },
  { code: "TFU", city: "Chengdu Tianfu", country: "China", countryCode: "CN" },
  { code: "CKG", city: "Chongqing", country: "China", countryCode: "CN" },
  { code: "KMG", city: "Kunming", country: "China", countryCode: "CN" },
  { code: "XIY", city: "Xi'an", country: "China", countryCode: "CN" },
  { code: "HGH", city: "Hangzhou", country: "China", countryCode: "CN" },
  { code: "NKG", city: "Nanjing", country: "China", countryCode: "CN" },
  { code: "WUH", city: "Wuhan", country: "China", countryCode: "CN" },
  { code: "CSX", city: "Changsha", country: "China", countryCode: "CN" },
  { code: "TSN", city: "Tianjin", country: "China", countryCode: "CN" },
  { code: "DLC", city: "Dalian", country: "China", countryCode: "CN" },
  { code: "SHE", city: "Shenyang", country: "China", countryCode: "CN" },
  { code: "TAO", city: "Qingdao", country: "China", countryCode: "CN" },
  { code: "XMN", city: "Xiamen", country: "China", countryCode: "CN" },
  { code: "HRB", city: "Harbin", country: "China", countryCode: "CN" },
  { code: "FOC", city: "Fuzhou", country: "China", countryCode: "CN" },
  { code: "ZUH", city: "Zhuhai", country: "China", countryCode: "CN" },
  { code: "NNG", city: "Nanning", country: "China", countryCode: "CN" },
  { code: "CGO", city: "Zhengzhou", country: "China", countryCode: "CN" },
  { code: "TNA", city: "Jinan", country: "China", countryCode: "CN" },
  { code: "SYX", city: "Sanya", country: "China", countryCode: "CN" },
  { code: "HAK", city: "Haikou", country: "China", countryCode: "CN" },
  { code: "URC", city: "Urumqi", country: "China", countryCode: "CN" },
  { code: "LHW", city: "Lanzhou", country: "China", countryCode: "CN" },
  { code: "HET", city: "Hohhot", country: "China", countryCode: "CN" },
  { code: "INC", city: "Yinchuan", country: "China", countryCode: "CN" },
  { code: "XNN", city: "Xining", country: "China", countryCode: "CN" },
  { code: "KWE", city: "Guiyang", country: "China", countryCode: "CN" },
  { code: "WNZ", city: "Wenzhou", country: "China", countryCode: "CN" },
  { code: "SWA", city: "Shantou", country: "China", countryCode: "CN" },
  { code: "NGB", city: "Ningbo", country: "China", countryCode: "CN" },
  { code: "TYN", city: "Taiyuan", country: "China", countryCode: "CN" },
  { code: "CGQ", city: "Changchun", country: "China", countryCode: "CN" },
  { code: "KHN", city: "Nanchang", country: "China", countryCode: "CN" },
  { code: "HFE", city: "Hefei", country: "China", countryCode: "CN" },
  { code: "LXA", city: "Lhasa", country: "China", countryCode: "CN" },
  { code: "HKG", city: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
  { code: "MFM", city: "Macau", country: "Macau", countryCode: "MO" },
  { code: "TPE", city: "Taipei Taoyuan", country: "Taiwan", countryCode: "TW" },
  { code: "TSA", city: "Taipei Songshan", country: "Taiwan", countryCode: "TW" },
  { code: "KHH", city: "Kaohsiung", country: "Taiwan", countryCode: "TW" },
  { code: "RMQ", city: "Taichung", country: "Taiwan", countryCode: "TW" },
  { code: "ICN", city: "Seoul Incheon", country: "South Korea", countryCode: "KR" },
  { code: "GMP", city: "Seoul Gimpo", country: "South Korea", countryCode: "KR" },
  { code: "PUS", city: "Busan", country: "South Korea", countryCode: "KR" },
  { code: "CJU", city: "Jeju", country: "South Korea", countryCode: "KR" },
  { code: "TAE", city: "Daegu", country: "South Korea", countryCode: "KR" },
  { code: "CJJ", city: "Cheongju", country: "South Korea", countryCode: "KR" },
  { code: "KWJ", city: "Gwangju", country: "South Korea", countryCode: "KR" },
  { code: "ULN", city: "Ulaanbaatar", country: "Mongolia", countryCode: "MN" },

  // ===== JAPAN =====
  { code: "NRT", city: "Tokyo Narita", country: "Japan", countryCode: "JP" },
  { code: "HND", city: "Tokyo Haneda", country: "Japan", countryCode: "JP" },
  { code: "KIX", city: "Osaka Kansai", country: "Japan", countryCode: "JP" },
  { code: "ITM", city: "Osaka Itami", country: "Japan", countryCode: "JP" },
  { code: "NGO", city: "Nagoya Chubu", country: "Japan", countryCode: "JP" },
  { code: "FUK", city: "Fukuoka", country: "Japan", countryCode: "JP" },
  { code: "CTS", city: "Sapporo Chitose", country: "Japan", countryCode: "JP" },
  { code: "OKA", city: "Okinawa Naha", country: "Japan", countryCode: "JP" },
  { code: "KOJ", city: "Kagoshima", country: "Japan", countryCode: "JP" },
  { code: "SDJ", city: "Sendai", country: "Japan", countryCode: "JP" },
  { code: "HIJ", city: "Hiroshima", country: "Japan", countryCode: "JP" },
  { code: "KMJ", city: "Kumamoto", country: "Japan", countryCode: "JP" },
  { code: "NGS", city: "Nagasaki", country: "Japan", countryCode: "JP" },
  { code: "OIT", city: "Oita", country: "Japan", countryCode: "JP" },
  { code: "TAK", city: "Takamatsu", country: "Japan", countryCode: "JP" },
  { code: "MYJ", city: "Matsuyama", country: "Japan", countryCode: "JP" },
  { code: "KMQ", city: "Komatsu", country: "Japan", countryCode: "JP" },
  { code: "AOJ", city: "Aomori", country: "Japan", countryCode: "JP" },
  { code: "AKJ", city: "Asahikawa", country: "Japan", countryCode: "JP" },
  { code: "KCZ", city: "Kochi", country: "Japan", countryCode: "JP" },

  // ===== NORTH AMERICA (US, Canada, Mexico, Caribbean, Central & South America) =====
  { code: "JFK", city: "New York JFK", country: "United States", countryCode: "US" },
  { code: "LAX", city: "Los Angeles", country: "United States", countryCode: "US" },
  { code: "ORD", city: "Chicago O'Hare", country: "United States", countryCode: "US" },
  { code: "ATL", city: "Atlanta", country: "United States", countryCode: "US" },
  { code: "DFW", city: "Dallas Fort Worth", country: "United States", countryCode: "US" },
  { code: "DEN", city: "Denver", country: "United States", countryCode: "US" },
  { code: "SFO", city: "San Francisco", country: "United States", countryCode: "US" },
  { code: "SEA", city: "Seattle", country: "United States", countryCode: "US" },
  { code: "LAS", city: "Las Vegas", country: "United States", countryCode: "US" },
  { code: "MIA", city: "Miami", country: "United States", countryCode: "US" },
  { code: "MCO", city: "Orlando", country: "United States", countryCode: "US" },
  { code: "EWR", city: "Newark", country: "United States", countryCode: "US" },
  { code: "BOS", city: "Boston", country: "United States", countryCode: "US" },
  { code: "MSP", city: "Minneapolis", country: "United States", countryCode: "US" },
  { code: "DTW", city: "Detroit", country: "United States", countryCode: "US" },
  { code: "PHL", city: "Philadelphia", country: "United States", countryCode: "US" },
  { code: "CLT", city: "Charlotte", country: "United States", countryCode: "US" },
  { code: "PHX", city: "Phoenix", country: "United States", countryCode: "US" },
  { code: "IAH", city: "Houston Intercontinental", country: "United States", countryCode: "US" },
  { code: "HOU", city: "Houston Hobby", country: "United States", countryCode: "US" },
  { code: "IAD", city: "Washington Dulles", country: "United States", countryCode: "US" },
  { code: "DCA", city: "Washington Reagan", country: "United States", countryCode: "US" },
  { code: "BWI", city: "Baltimore", country: "United States", countryCode: "US" },
  { code: "SAN", city: "San Diego", country: "United States", countryCode: "US" },
  { code: "TPA", city: "Tampa", country: "United States", countryCode: "US" },
  { code: "SLC", city: "Salt Lake City", country: "United States", countryCode: "US" },
  { code: "PDX", city: "Portland", country: "United States", countryCode: "US" },
  { code: "STL", city: "St. Louis", country: "United States", countryCode: "US" },
  { code: "AUS", city: "Austin", country: "United States", countryCode: "US" },
  { code: "BNA", city: "Nashville", country: "United States", countryCode: "US" },
  { code: "RDU", city: "Raleigh-Durham", country: "United States", countryCode: "US" },
  { code: "SMF", city: "Sacramento", country: "United States", countryCode: "US" },
  { code: "SJC", city: "San Jose", country: "United States", countryCode: "US" },
  { code: "IND", city: "Indianapolis", country: "United States", countryCode: "US" },
  { code: "MCI", city: "Kansas City", country: "United States", countryCode: "US" },
  { code: "CMH", city: "Columbus", country: "United States", countryCode: "US" },
  { code: "CLE", city: "Cleveland", country: "United States", countryCode: "US" },
  { code: "PIT", city: "Pittsburgh", country: "United States", countryCode: "US" },
  { code: "CVG", city: "Cincinnati", country: "United States", countryCode: "US" },
  { code: "MSY", city: "New Orleans", country: "United States", countryCode: "US" },
  { code: "MKE", city: "Milwaukee", country: "United States", countryCode: "US" },
  { code: "OAK", city: "Oakland", country: "United States", countryCode: "US" },
  { code: "JAX", city: "Jacksonville", country: "United States", countryCode: "US" },
  { code: "RSW", city: "Fort Myers", country: "United States", countryCode: "US" },
  { code: "FLL", city: "Fort Lauderdale", country: "United States", countryCode: "US" },
  { code: "PBI", city: "West Palm Beach", country: "United States", countryCode: "US" },
  { code: "ABQ", city: "Albuquerque", country: "United States", countryCode: "US" },
  { code: "OMA", city: "Omaha", country: "United States", countryCode: "US" },
  { code: "MEM", city: "Memphis", country: "United States", countryCode: "US" },
  { code: "RNO", city: "Reno", country: "United States", countryCode: "US" },
  { code: "SNA", city: "Santa Ana", country: "United States", countryCode: "US" },
  { code: "BUF", city: "Buffalo", country: "United States", countryCode: "US" },
  { code: "ANC", city: "Anchorage", country: "United States", countryCode: "US" },
  { code: "HNL", city: "Honolulu", country: "United States", countryCode: "US" },
  { code: "OGG", city: "Maui Kahului", country: "United States", countryCode: "US" },
  { code: "LIH", city: "Lihue Kauai", country: "United States", countryCode: "US" },
  { code: "KOA", city: "Kona", country: "United States", countryCode: "US" },
  { code: "GUM", city: "Guam", country: "United States", countryCode: "US" },
  { code: "YYZ", city: "Toronto Pearson", country: "Canada", countryCode: "CA" },
  { code: "YVR", city: "Vancouver", country: "Canada", countryCode: "CA" },
  { code: "YUL", city: "Montreal", country: "Canada", countryCode: "CA" },
  { code: "YYC", city: "Calgary", country: "Canada", countryCode: "CA" },
  { code: "YEG", city: "Edmonton", country: "Canada", countryCode: "CA" },
  { code: "YOW", city: "Ottawa", country: "Canada", countryCode: "CA" },
  { code: "YWG", city: "Winnipeg", country: "Canada", countryCode: "CA" },
  { code: "YHZ", city: "Halifax", country: "Canada", countryCode: "CA" },
  { code: "YQB", city: "Quebec City", country: "Canada", countryCode: "CA" },
  { code: "YKA", city: "Kamloops", country: "Canada", countryCode: "CA" },
  { code: "YXE", city: "Saskatoon", country: "Canada", countryCode: "CA" },
  { code: "YQR", city: "Regina", country: "Canada", countryCode: "CA" },
  { code: "YYJ", city: "Victoria", country: "Canada", countryCode: "CA" },
  { code: "YLW", city: "Kelowna", country: "Canada", countryCode: "CA" },
  { code: "MEX", city: "Mexico City", country: "Mexico", countryCode: "MX" },
  { code: "CUN", city: "Cancun", country: "Mexico", countryCode: "MX" },
  { code: "GDL", city: "Guadalajara", country: "Mexico", countryCode: "MX" },
  { code: "MTY", city: "Monterrey", country: "Mexico", countryCode: "MX" },
  { code: "TIJ", city: "Tijuana", country: "Mexico", countryCode: "MX" },
  { code: "SJD", city: "San Jose del Cabo", country: "Mexico", countryCode: "MX" },
  { code: "PVR", city: "Puerto Vallarta", country: "Mexico", countryCode: "MX" },
  { code: "MID", city: "Merida", country: "Mexico", countryCode: "MX" },
  { code: "GRU", city: "Sao Paulo Guarulhos", country: "Brazil", countryCode: "BR" },
  { code: "GIG", city: "Rio de Janeiro", country: "Brazil", countryCode: "BR" },
  { code: "BSB", city: "Brasilia", country: "Brazil", countryCode: "BR" },
  { code: "CNF", city: "Belo Horizonte", country: "Brazil", countryCode: "BR" },
  { code: "POA", city: "Porto Alegre", country: "Brazil", countryCode: "BR" },
  { code: "SSA", city: "Salvador", country: "Brazil", countryCode: "BR" },
  { code: "REC", city: "Recife", country: "Brazil", countryCode: "BR" },
  { code: "FOR", city: "Fortaleza", country: "Brazil", countryCode: "BR" },
  { code: "CWB", city: "Curitiba", country: "Brazil", countryCode: "BR" },
  { code: "CGH", city: "Sao Paulo Congonhas", country: "Brazil", countryCode: "BR" },
  { code: "VCP", city: "Campinas", country: "Brazil", countryCode: "BR" },
  { code: "EZE", city: "Buenos Aires Ezeiza", country: "Argentina", countryCode: "AR" },
  { code: "AEP", city: "Buenos Aires Aeroparque", country: "Argentina", countryCode: "AR" },
  { code: "COR", city: "Cordoba", country: "Argentina", countryCode: "AR" },
  { code: "MDZ", city: "Mendoza", country: "Argentina", countryCode: "AR" },
  { code: "SCL", city: "Santiago", country: "Chile", countryCode: "CL" },
  { code: "LIM", city: "Lima", country: "Peru", countryCode: "PE" },
  { code: "CUZ", city: "Cusco", country: "Peru", countryCode: "PE" },
  { code: "BOG", city: "Bogota", country: "Colombia", countryCode: "CO" },
  { code: "MDE", city: "Medellin", country: "Colombia", countryCode: "CO" },
  { code: "CTG", city: "Cartagena", country: "Colombia", countryCode: "CO" },
  { code: "CLO", city: "Cali", country: "Colombia", countryCode: "CO" },
  { code: "UIO", city: "Quito", country: "Ecuador", countryCode: "EC" },
  { code: "GYE", city: "Guayaquil", country: "Ecuador", countryCode: "EC" },
  { code: "CCS", city: "Caracas", country: "Venezuela", countryCode: "VE" },
  { code: "MVD", city: "Montevideo", country: "Uruguay", countryCode: "UY" },
  { code: "ASU", city: "Asuncion", country: "Paraguay", countryCode: "PY" },
  { code: "LPB", city: "La Paz", country: "Bolivia", countryCode: "BO" },
  { code: "VVI", city: "Santa Cruz", country: "Bolivia", countryCode: "BO" },
  { code: "PTY", city: "Panama City", country: "Panama", countryCode: "PA" },
  { code: "SJO", city: "San Jose", country: "Costa Rica", countryCode: "CR" },
  { code: "SAL", city: "San Salvador", country: "El Salvador", countryCode: "SV" },
  { code: "GUA", city: "Guatemala City", country: "Guatemala", countryCode: "GT" },
  { code: "TGU", city: "Tegucigalpa", country: "Honduras", countryCode: "HN" },
  { code: "MGA", city: "Managua", country: "Nicaragua", countryCode: "NI" },
  { code: "BZE", city: "Belize City", country: "Belize", countryCode: "BZ" },
  { code: "HAV", city: "Havana", country: "Cuba", countryCode: "CU" },
  { code: "SDQ", city: "Santo Domingo", country: "Dominican Republic", countryCode: "DO" },
  { code: "PUJ", city: "Punta Cana", country: "Dominican Republic", countryCode: "DO" },
  { code: "SJU", city: "San Juan", country: "Puerto Rico", countryCode: "PR" },
  { code: "KIN", city: "Kingston", country: "Jamaica", countryCode: "JM" },
  { code: "MBJ", city: "Montego Bay", country: "Jamaica", countryCode: "JM" },
  { code: "NAS", city: "Nassau", country: "Bahamas", countryCode: "BS" },
  { code: "POS", city: "Port of Spain", country: "Trinidad and Tobago", countryCode: "TT" },
  { code: "BGI", city: "Bridgetown", country: "Barbados", countryCode: "BB" },
  { code: "AUA", city: "Aruba", country: "Aruba", countryCode: "AW" },
  { code: "CUR", city: "Curacao", country: "Curacao", countryCode: "CW" },
  { code: "PPT", city: "Papeete Tahiti", country: "French Polynesia", countryCode: "PF" },
  { code: "NAN", city: "Nadi", country: "Fiji", countryCode: "FJ" },

  // ===== EUROPE =====
  { code: "LHR", city: "London Heathrow", country: "United Kingdom", countryCode: "GB" },
  { code: "LGW", city: "London Gatwick", country: "United Kingdom", countryCode: "GB" },
  { code: "STN", city: "London Stansted", country: "United Kingdom", countryCode: "GB" },
  { code: "LTN", city: "London Luton", country: "United Kingdom", countryCode: "GB" },
  { code: "LCY", city: "London City", country: "United Kingdom", countryCode: "GB" },
  { code: "MAN", city: "Manchester", country: "United Kingdom", countryCode: "GB" },
  { code: "EDI", city: "Edinburgh", country: "United Kingdom", countryCode: "GB" },
  { code: "BHX", city: "Birmingham", country: "United Kingdom", countryCode: "GB" },
  { code: "GLA", city: "Glasgow", country: "United Kingdom", countryCode: "GB" },
  { code: "BRS", city: "Bristol", country: "United Kingdom", countryCode: "GB" },
  { code: "NCL", city: "Newcastle", country: "United Kingdom", countryCode: "GB" },
  { code: "BFS", city: "Belfast", country: "United Kingdom", countryCode: "GB" },
  { code: "LPL", city: "Liverpool", country: "United Kingdom", countryCode: "GB" },
  { code: "ABZ", city: "Aberdeen", country: "United Kingdom", countryCode: "GB" },
  { code: "CDG", city: "Paris Charles de Gaulle", country: "France", countryCode: "FR" },
  { code: "ORY", city: "Paris Orly", country: "France", countryCode: "FR" },
  { code: "NCE", city: "Nice", country: "France", countryCode: "FR" },
  { code: "LYS", city: "Lyon", country: "France", countryCode: "FR" },
  { code: "MRS", city: "Marseille", country: "France", countryCode: "FR" },
  { code: "TLS", city: "Toulouse", country: "France", countryCode: "FR" },
  { code: "BOD", city: "Bordeaux", country: "France", countryCode: "FR" },
  { code: "NTE", city: "Nantes", country: "France", countryCode: "FR" },
  { code: "SXB", city: "Strasbourg", country: "France", countryCode: "FR" },
  { code: "FRA", city: "Frankfurt", country: "Germany", countryCode: "DE" },
  { code: "MUC", city: "Munich", country: "Germany", countryCode: "DE" },
  { code: "BER", city: "Berlin Brandenburg", country: "Germany", countryCode: "DE" },
  { code: "DUS", city: "Dusseldorf", country: "Germany", countryCode: "DE" },
  { code: "HAM", city: "Hamburg", country: "Germany", countryCode: "DE" },
  { code: "CGN", city: "Cologne", country: "Germany", countryCode: "DE" },
  { code: "STR", city: "Stuttgart", country: "Germany", countryCode: "DE" },
  { code: "HAJ", city: "Hannover", country: "Germany", countryCode: "DE" },
  { code: "NUE", city: "Nuremberg", country: "Germany", countryCode: "DE" },
  { code: "LEJ", city: "Leipzig", country: "Germany", countryCode: "DE" },
  { code: "AMS", city: "Amsterdam Schiphol", country: "Netherlands", countryCode: "NL" },
  { code: "EIN", city: "Eindhoven", country: "Netherlands", countryCode: "NL" },
  { code: "RTM", city: "Rotterdam", country: "Netherlands", countryCode: "NL" },
  { code: "MAD", city: "Madrid Barajas", country: "Spain", countryCode: "ES" },
  { code: "BCN", city: "Barcelona", country: "Spain", countryCode: "ES" },
  { code: "PMI", city: "Palma Mallorca", country: "Spain", countryCode: "ES" },
  { code: "AGP", city: "Malaga", country: "Spain", countryCode: "ES" },
  { code: "ALC", city: "Alicante", country: "Spain", countryCode: "ES" },
  { code: "TFS", city: "Tenerife South", country: "Spain", countryCode: "ES" },
  { code: "LPA", city: "Gran Canaria", country: "Spain", countryCode: "ES" },
  { code: "IBZ", city: "Ibiza", country: "Spain", countryCode: "ES" },
  { code: "SVQ", city: "Seville", country: "Spain", countryCode: "ES" },
  { code: "VLC", city: "Valencia", country: "Spain", countryCode: "ES" },
  { code: "BIO", city: "Bilbao", country: "Spain", countryCode: "ES" },
  { code: "FCO", city: "Rome Fiumicino", country: "Italy", countryCode: "IT" },
  { code: "MXP", city: "Milan Malpensa", country: "Italy", countryCode: "IT" },
  { code: "LIN", city: "Milan Linate", country: "Italy", countryCode: "IT" },
  { code: "VCE", city: "Venice", country: "Italy", countryCode: "IT" },
  { code: "NAP", city: "Naples", country: "Italy", countryCode: "IT" },
  { code: "FLR", city: "Florence", country: "Italy", countryCode: "IT" },
  { code: "BLQ", city: "Bologna", country: "Italy", countryCode: "IT" },
  { code: "PSA", city: "Pisa", country: "Italy", countryCode: "IT" },
  { code: "CTA", city: "Catania", country: "Italy", countryCode: "IT" },
  { code: "PMO", city: "Palermo", country: "Italy", countryCode: "IT" },
  { code: "BGY", city: "Milan Bergamo", country: "Italy", countryCode: "IT" },
  { code: "TRN", city: "Turin", country: "Italy", countryCode: "IT" },
  { code: "LIS", city: "Lisbon", country: "Portugal", countryCode: "PT" },
  { code: "OPO", city: "Porto", country: "Portugal", countryCode: "PT" },
  { code: "FAO", city: "Faro", country: "Portugal", countryCode: "PT" },
  { code: "FNC", city: "Funchal Madeira", country: "Portugal", countryCode: "PT" },
  { code: "ZRH", city: "Zurich", country: "Switzerland", countryCode: "CH" },
  { code: "GVA", city: "Geneva", country: "Switzerland", countryCode: "CH" },
  { code: "BSL", city: "Basel", country: "Switzerland", countryCode: "CH" },
  { code: "BRN", city: "Bern", country: "Switzerland", countryCode: "CH" },
  { code: "VIE", city: "Vienna", country: "Austria", countryCode: "AT" },
  { code: "SZG", city: "Salzburg", country: "Austria", countryCode: "AT" },
  { code: "INN", city: "Innsbruck", country: "Austria", countryCode: "AT" },
  { code: "GRZ", city: "Graz", country: "Austria", countryCode: "AT" },
  { code: "BRU", city: "Brussels", country: "Belgium", countryCode: "BE" },
  { code: "CRL", city: "Brussels Charleroi", country: "Belgium", countryCode: "BE" },
  { code: "LUX", city: "Luxembourg", country: "Luxembourg", countryCode: "LU" },
  { code: "DUB", city: "Dublin", country: "Ireland", countryCode: "IE" },
  { code: "SNN", city: "Shannon", country: "Ireland", countryCode: "IE" },
  { code: "ORK", city: "Cork", country: "Ireland", countryCode: "IE" },
  { code: "CPH", city: "Copenhagen", country: "Denmark", countryCode: "DK" },
  { code: "BLL", city: "Billund", country: "Denmark", countryCode: "DK" },
  { code: "OSL", city: "Oslo Gardermoen", country: "Norway", countryCode: "NO" },
  { code: "BGO", city: "Bergen", country: "Norway", countryCode: "NO" },
  { code: "TRD", city: "Trondheim", country: "Norway", countryCode: "NO" },
  { code: "SVG", city: "Stavanger", country: "Norway", countryCode: "NO" },
  { code: "TOS", city: "Tromso", country: "Norway", countryCode: "NO" },
  { code: "ARN", city: "Stockholm Arlanda", country: "Sweden", countryCode: "SE" },
  { code: "GOT", city: "Gothenburg", country: "Sweden", countryCode: "SE" },
  { code: "MMX", city: "Malmo", country: "Sweden", countryCode: "SE" },
  { code: "HEL", city: "Helsinki", country: "Finland", countryCode: "FI" },
  { code: "TMP", city: "Tampere", country: "Finland", countryCode: "FI" },
  { code: "OUL", city: "Oulu", country: "Finland", countryCode: "FI" },
  { code: "RVN", city: "Rovaniemi", country: "Finland", countryCode: "FI" },
  { code: "KEF", city: "Reykjavik Keflavik", country: "Iceland", countryCode: "IS" },
  { code: "ATH", city: "Athens", country: "Greece", countryCode: "GR" },
  { code: "SKG", city: "Thessaloniki", country: "Greece", countryCode: "GR" },
  { code: "HER", city: "Heraklion Crete", country: "Greece", countryCode: "GR" },
  { code: "RHO", city: "Rhodes", country: "Greece", countryCode: "GR" },
  { code: "CFU", city: "Corfu", country: "Greece", countryCode: "GR" },
  { code: "JMK", city: "Mykonos", country: "Greece", countryCode: "GR" },
  { code: "JTR", city: "Santorini", country: "Greece", countryCode: "GR" },
  { code: "IST", city: "Istanbul", country: "Turkey", countryCode: "TR" },
  { code: "SAW", city: "Istanbul Sabiha", country: "Turkey", countryCode: "TR" },
  { code: "AYT", city: "Antalya", country: "Turkey", countryCode: "TR" },
  { code: "ESB", city: "Ankara", country: "Turkey", countryCode: "TR" },
  { code: "ADB", city: "Izmir", country: "Turkey", countryCode: "TR" },
  { code: "DLM", city: "Dalaman", country: "Turkey", countryCode: "TR" },
  { code: "TZX", city: "Trabzon", country: "Turkey", countryCode: "TR" },
  { code: "WAW", city: "Warsaw Chopin", country: "Poland", countryCode: "PL" },
  { code: "KRK", city: "Krakow", country: "Poland", countryCode: "PL" },
  { code: "WRO", city: "Wroclaw", country: "Poland", countryCode: "PL" },
  { code: "GDN", city: "Gdansk", country: "Poland", countryCode: "PL" },
  { code: "KTW", city: "Katowice", country: "Poland", countryCode: "PL" },
  { code: "POZ", city: "Poznan", country: "Poland", countryCode: "PL" },
  { code: "PRG", city: "Prague", country: "Czech Republic", countryCode: "CZ" },
  { code: "BUD", city: "Budapest", country: "Hungary", countryCode: "HU" },
  { code: "OTP", city: "Bucharest", country: "Romania", countryCode: "RO" },
  { code: "CLJ", city: "Cluj-Napoca", country: "Romania", countryCode: "RO" },
  { code: "SOF", city: "Sofia", country: "Bulgaria", countryCode: "BG" },
  { code: "VAR", city: "Varna", country: "Bulgaria", countryCode: "BG" },
  { code: "BEG", city: "Belgrade", country: "Serbia", countryCode: "RS" },
  { code: "ZAG", city: "Zagreb", country: "Croatia", countryCode: "HR" },
  { code: "SPU", city: "Split", country: "Croatia", countryCode: "HR" },
  { code: "DBV", city: "Dubrovnik", country: "Croatia", countryCode: "HR" },
  { code: "LJU", city: "Ljubljana", country: "Slovenia", countryCode: "SI" },
  { code: "SKP", city: "Skopje", country: "North Macedonia", countryCode: "MK" },
  { code: "TIA", city: "Tirana", country: "Albania", countryCode: "AL" },
  { code: "BTS", city: "Bratislava", country: "Slovakia", countryCode: "SK" },
  { code: "TLL", city: "Tallinn", country: "Estonia", countryCode: "EE" },
  { code: "RIX", city: "Riga", country: "Latvia", countryCode: "LV" },
  { code: "VNO", city: "Vilnius", country: "Lithuania", countryCode: "LT" },
  { code: "KBP", city: "Kyiv Boryspil", country: "Ukraine", countryCode: "UA" },
  { code: "SVO", city: "Moscow Sheremetyevo", country: "Russia", countryCode: "RU" },
  { code: "DME", city: "Moscow Domodedovo", country: "Russia", countryCode: "RU" },
  { code: "VKO", city: "Moscow Vnukovo", country: "Russia", countryCode: "RU" },
  { code: "LED", city: "St. Petersburg", country: "Russia", countryCode: "RU" },
  { code: "AER", city: "Sochi", country: "Russia", countryCode: "RU" },
  { code: "KZN", city: "Kazan", country: "Russia", countryCode: "RU" },
  { code: "SVX", city: "Yekaterinburg", country: "Russia", countryCode: "RU" },
  { code: "OVB", city: "Novosibirsk", country: "Russia", countryCode: "RU" },
  { code: "VVO", city: "Vladivostok", country: "Russia", countryCode: "RU" },
  { code: "IKT", city: "Irkutsk", country: "Russia", countryCode: "RU" },
  { code: "KJA", city: "Krasnoyarsk", country: "Russia", countryCode: "RU" },
  { code: "MRV", city: "Mineralnye Vody", country: "Russia", countryCode: "RU" },
  { code: "ROV", city: "Rostov-on-Don", country: "Russia", countryCode: "RU" },
  { code: "GEL", city: "Gelendzhik", country: "Russia", countryCode: "RU" },
  { code: "TBS", city: "Tbilisi", country: "Georgia", countryCode: "GE" },
  { code: "EVN", city: "Yerevan", country: "Armenia", countryCode: "AM" },
  { code: "GYD", city: "Baku", country: "Azerbaijan", countryCode: "AZ" },
  { code: "MLA", city: "Malta", country: "Malta", countryCode: "MT" },
  { code: "LCA", city: "Larnaca", country: "Cyprus", countryCode: "CY" },
  { code: "PFO", city: "Paphos", country: "Cyprus", countryCode: "CY" },

  // ===== MIDDLE EAST =====
  { code: "DXB", city: "Dubai", country: "United Arab Emirates", countryCode: "AE" },
  { code: "AUH", city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE" },
  { code: "SHJ", city: "Sharjah", country: "United Arab Emirates", countryCode: "AE" },
  { code: "DWC", city: "Dubai World Central", country: "United Arab Emirates", countryCode: "AE" },
  { code: "RKT", city: "Ras Al Khaimah", country: "United Arab Emirates", countryCode: "AE" },
  { code: "DOH", city: "Doha Hamad", country: "Qatar", countryCode: "QA" },
  { code: "RUH", city: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
  { code: "JED", city: "Jeddah", country: "Saudi Arabia", countryCode: "SA" },
  { code: "DMM", city: "Dammam", country: "Saudi Arabia", countryCode: "SA" },
  { code: "MED", city: "Medina", country: "Saudi Arabia", countryCode: "SA" },
  { code: "BAH", city: "Bahrain", country: "Bahrain", countryCode: "BH" },
  { code: "KWI", city: "Kuwait", country: "Kuwait", countryCode: "KW" },
  { code: "MCT", city: "Muscat", country: "Oman", countryCode: "OM" },
  { code: "SLL", city: "Salalah", country: "Oman", countryCode: "OM" },
  { code: "AMM", city: "Amman", country: "Jordan", countryCode: "JO" },
  { code: "AQJ", city: "Aqaba", country: "Jordan", countryCode: "JO" },
  { code: "BEY", city: "Beirut", country: "Lebanon", countryCode: "LB" },
  { code: "TLV", city: "Tel Aviv", country: "Israel", countryCode: "IL" },
  { code: "CAI", city: "Cairo", country: "Egypt", countryCode: "EG" },
  { code: "HRG", city: "Hurghada", country: "Egypt", countryCode: "EG" },
  { code: "SSH", city: "Sharm El Sheikh", country: "Egypt", countryCode: "EG" },
  { code: "LXR", city: "Luxor", country: "Egypt", countryCode: "EG" },
  { code: "ALG", city: "Algiers", country: "Algeria", countryCode: "DZ" },
  { code: "CMN", city: "Casablanca", country: "Morocco", countryCode: "MA" },
  { code: "RAK", city: "Marrakech", country: "Morocco", countryCode: "MA" },
  { code: "TNG", city: "Tangier", country: "Morocco", countryCode: "MA" },
  { code: "FEZ", city: "Fez", country: "Morocco", countryCode: "MA" },
  { code: "TUN", city: "Tunis", country: "Tunisia", countryCode: "TN" },
  { code: "TIP", city: "Tripoli", country: "Libya", countryCode: "LY" },
  { code: "BGW", city: "Baghdad", country: "Iraq", countryCode: "IQ" },
  { code: "EBL", city: "Erbil", country: "Iraq", countryCode: "IQ" },
  { code: "BSR", city: "Basra", country: "Iraq", countryCode: "IQ" },
  { code: "IKA", city: "Tehran Imam Khomeini", country: "Iran", countryCode: "IR" },
  { code: "THR", city: "Tehran Mehrabad", country: "Iran", countryCode: "IR" },
  { code: "MHD", city: "Mashhad", country: "Iran", countryCode: "IR" },
  { code: "SYZ", city: "Shiraz", country: "Iran", countryCode: "IR" },
  { code: "IFN", city: "Isfahan", country: "Iran", countryCode: "IR" },
  { code: "NJF", city: "Najaf", country: "Iraq", countryCode: "IQ" },
  { code: "KRT", city: "Khartoum", country: "Sudan", countryCode: "SD" },
  { code: "ADD", city: "Addis Ababa", country: "Ethiopia", countryCode: "ET" },

  // ===== SOUTH AFRICA =====
  { code: "JNB", city: "Johannesburg", country: "South Africa", countryCode: "ZA" },
  { code: "CPT", city: "Cape Town", country: "South Africa", countryCode: "ZA" },
  { code: "DUR", city: "Durban", country: "South Africa", countryCode: "ZA" },
  { code: "PLZ", city: "Port Elizabeth", country: "South Africa", countryCode: "ZA" },
  { code: "ELS", city: "East London", country: "South Africa", countryCode: "ZA" },
  { code: "BFN", city: "Bloemfontein", country: "South Africa", countryCode: "ZA" },
  { code: "GRJ", city: "George", country: "South Africa", countryCode: "ZA" },
  { code: "NBO", city: "Nairobi", country: "Kenya", countryCode: "KE" },
  { code: "MBA", city: "Mombasa", country: "Kenya", countryCode: "KE" },
  { code: "LOS", city: "Lagos", country: "Nigeria", countryCode: "NG" },
  { code: "ABV", city: "Abuja", country: "Nigeria", countryCode: "NG" },
  { code: "PHC", city: "Port Harcourt", country: "Nigeria", countryCode: "NG" },
  { code: "ACC", city: "Accra", country: "Ghana", countryCode: "GH" },
  { code: "DAR", city: "Dar es Salaam", country: "Tanzania", countryCode: "TZ" },
  { code: "JRO", city: "Kilimanjaro", country: "Tanzania", countryCode: "TZ" },
  { code: "ZNZ", city: "Zanzibar", country: "Tanzania", countryCode: "TZ" },
  { code: "EBB", city: "Entebbe", country: "Uganda", countryCode: "UG" },
  { code: "MPM", city: "Maputo", country: "Mozambique", countryCode: "MZ" },
  { code: "LLW", city: "Lilongwe", country: "Malawi", countryCode: "MW" },
  { code: "HRE", city: "Harare", country: "Zimbabwe", countryCode: "ZW" },
  { code: "VFA", city: "Victoria Falls", country: "Zimbabwe", countryCode: "ZW" },
  { code: "LUN", city: "Lusaka", country: "Zambia", countryCode: "ZM" },
  { code: "GBE", city: "Gaborone", country: "Botswana", countryCode: "BW" },
  { code: "WDH", city: "Windhoek", country: "Namibia", countryCode: "NA" },
  { code: "MRU", city: "Mauritius", country: "Mauritius", countryCode: "MU" },
  { code: "TNR", city: "Antananarivo", country: "Madagascar", countryCode: "MG" },
  { code: "SEZ", city: "Seychelles", country: "Seychelles", countryCode: "SC" },
  { code: "DSS", city: "Dakar", country: "Senegal", countryCode: "SN" },
  { code: "ABJ", city: "Abidjan", country: "Ivory Coast", countryCode: "CI" },
  { code: "DKR", city: "Dakar", country: "Senegal", countryCode: "SN" },
  { code: "ROB", city: "Monrovia", country: "Liberia", countryCode: "LR" },
  { code: "DLA", city: "Douala", country: "Cameroon", countryCode: "CM" },
  { code: "FIH", city: "Kinshasa", country: "DR Congo", countryCode: "CD" },
  { code: "BZV", city: "Brazzaville", country: "Congo", countryCode: "CG" },
  { code: "LBV", city: "Libreville", country: "Gabon", countryCode: "GA" },
  { code: "RUN", city: "Saint-Denis Reunion", country: "Reunion", countryCode: "RE" },
  { code: "KGL", city: "Kigali", country: "Rwanda", countryCode: "RW" },

  // ===== SOUTH ASIA =====
  { code: "DEL", city: "Delhi", country: "India", countryCode: "IN" },
  { code: "BOM", city: "Mumbai", country: "India", countryCode: "IN" },
  { code: "BLR", city: "Bengaluru", country: "India", countryCode: "IN" },
  { code: "MAA", city: "Chennai", country: "India", countryCode: "IN" },
  { code: "CCU", city: "Kolkata", country: "India", countryCode: "IN" },
  { code: "HYD", city: "Hyderabad", country: "India", countryCode: "IN" },
  { code: "COK", city: "Kochi", country: "India", countryCode: "IN" },
  { code: "AMD", city: "Ahmedabad", country: "India", countryCode: "IN" },
  { code: "PNQ", city: "Pune", country: "India", countryCode: "IN" },
  { code: "GOI", city: "Goa", country: "India", countryCode: "IN" },
  { code: "JAI", city: "Jaipur", country: "India", countryCode: "IN" },
  { code: "LKO", city: "Lucknow", country: "India", countryCode: "IN" },
  { code: "TRV", city: "Trivandrum", country: "India", countryCode: "IN" },
  { code: "GAU", city: "Guwahati", country: "India", countryCode: "IN" },
  { code: "NAG", city: "Nagpur", country: "India", countryCode: "IN" },
  { code: "PAT", city: "Patna", country: "India", countryCode: "IN" },
  { code: "VNS", city: "Varanasi", country: "India", countryCode: "IN" },
  { code: "IXC", city: "Chandigarh", country: "India", countryCode: "IN" },
  { code: "SXR", city: "Srinagar", country: "India", countryCode: "IN" },
  { code: "IXB", city: "Bagdogra", country: "India", countryCode: "IN" },
  { code: "BBI", city: "Bhubaneswar", country: "India", countryCode: "IN" },
  { code: "IXR", city: "Ranchi", country: "India", countryCode: "IN" },
  { code: "IDR", city: "Indore", country: "India", countryCode: "IN" },
  { code: "VTZ", city: "Visakhapatnam", country: "India", countryCode: "IN" },
  { code: "RPR", city: "Raipur", country: "India", countryCode: "IN" },
  { code: "CCJ", city: "Calicut", country: "India", countryCode: "IN" },
  { code: "CJB", city: "Coimbatore", country: "India", countryCode: "IN" },
  { code: "TRZ", city: "Tiruchirappalli", country: "India", countryCode: "IN" },
  { code: "MNG", city: "Mangalore", country: "India", countryCode: "IN" },
  { code: "IXE", city: "Mangalore", country: "India", countryCode: "IN" },
  { code: "UDR", city: "Udaipur", country: "India", countryCode: "IN" },
  { code: "ISB", city: "Islamabad", country: "Pakistan", countryCode: "PK" },
  { code: "KHI", city: "Karachi", country: "Pakistan", countryCode: "PK" },
  { code: "LHE", city: "Lahore", country: "Pakistan", countryCode: "PK" },
  { code: "PEW", city: "Peshawar", country: "Pakistan", countryCode: "PK" },
  { code: "MUX", city: "Multan", country: "Pakistan", countryCode: "PK" },
  { code: "SKT", city: "Sialkot", country: "Pakistan", countryCode: "PK" },
  { code: "FSD", city: "Faisalabad", country: "Pakistan", countryCode: "PK" },
  { code: "DAC", city: "Dhaka", country: "Bangladesh", countryCode: "BD" },
  { code: "CGP", city: "Chittagong", country: "Bangladesh", countryCode: "BD" },
  { code: "CMB", city: "Colombo", country: "Sri Lanka", countryCode: "LK" },
  { code: "MLE", city: "Male", country: "Maldives", countryCode: "MV" },
  { code: "KTM", city: "Kathmandu", country: "Nepal", countryCode: "NP" },
  { code: "PBH", city: "Paro", country: "Bhutan", countryCode: "BT" },

  // ===== SOUTHEAST ASIA =====
  { code: "SIN", city: "Singapore Changi", country: "Singapore", countryCode: "SG" },
  { code: "KUL", city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
  { code: "PEN", city: "Penang", country: "Malaysia", countryCode: "MY" },
  { code: "LGK", city: "Langkawi", country: "Malaysia", countryCode: "MY" },
  { code: "BKI", city: "Kota Kinabalu", country: "Malaysia", countryCode: "MY" },
  { code: "KCH", city: "Kuching", country: "Malaysia", countryCode: "MY" },
  { code: "JHB", city: "Johor Bahru", country: "Malaysia", countryCode: "MY" },
  { code: "SZB", city: "Subang", country: "Malaysia", countryCode: "MY" },
  { code: "MYY", city: "Miri", country: "Malaysia", countryCode: "MY" },
  { code: "IPH", city: "Ipoh", country: "Malaysia", countryCode: "MY" },
  { code: "BKK", city: "Bangkok Suvarnabhumi", country: "Thailand", countryCode: "TH" },
  { code: "DMK", city: "Bangkok Don Mueang", country: "Thailand", countryCode: "TH" },
  { code: "HKT", city: "Phuket", country: "Thailand", countryCode: "TH" },
  { code: "CNX", city: "Chiang Mai", country: "Thailand", countryCode: "TH" },
  { code: "CEI", city: "Chiang Rai", country: "Thailand", countryCode: "TH" },
  { code: "USM", city: "Koh Samui", country: "Thailand", countryCode: "TH" },
  { code: "HDY", city: "Hat Yai", country: "Thailand", countryCode: "TH" },
  { code: "KBV", city: "Krabi", country: "Thailand", countryCode: "TH" },
  { code: "UTP", city: "Pattaya", country: "Thailand", countryCode: "TH" },
  { code: "CGK", city: "Jakarta Soekarno-Hatta", country: "Indonesia", countryCode: "ID" },
  { code: "DPS", city: "Bali Ngurah Rai", country: "Indonesia", countryCode: "ID" },
  { code: "SUB", city: "Surabaya", country: "Indonesia", countryCode: "ID" },
  { code: "UPG", city: "Makassar", country: "Indonesia", countryCode: "ID" },
  { code: "KNO", city: "Medan Kualanamu", country: "Indonesia", countryCode: "ID" },
  { code: "JOG", city: "Yogyakarta", country: "Indonesia", countryCode: "ID" },
  { code: "BDO", city: "Bandung", country: "Indonesia", countryCode: "ID" },
  { code: "SOC", city: "Solo", country: "Indonesia", countryCode: "ID" },
  { code: "PLM", city: "Palembang", country: "Indonesia", countryCode: "ID" },
  { code: "BPN", city: "Balikpapan", country: "Indonesia", countryCode: "ID" },
  { code: "PDG", city: "Padang", country: "Indonesia", countryCode: "ID" },
  { code: "PKU", city: "Pekanbaru", country: "Indonesia", countryCode: "ID" },
  { code: "BTH", city: "Batam", country: "Indonesia", countryCode: "ID" },
  { code: "LOP", city: "Lombok", country: "Indonesia", countryCode: "ID" },
  { code: "MNL", city: "Manila", country: "Philippines", countryCode: "PH" },
  { code: "CEB", city: "Cebu", country: "Philippines", countryCode: "PH" },
  { code: "DVO", city: "Davao", country: "Philippines", countryCode: "PH" },
  { code: "CRK", city: "Clark", country: "Philippines", countryCode: "PH" },
  { code: "ILO", city: "Iloilo", country: "Philippines", countryCode: "PH" },
  { code: "KLO", city: "Kalibo", country: "Philippines", countryCode: "PH" },
  { code: "BCD", city: "Bacolod", country: "Philippines", countryCode: "PH" },
  { code: "TAG", city: "Tagbilaran", country: "Philippines", countryCode: "PH" },
  { code: "PPS", city: "Puerto Princesa", country: "Philippines", countryCode: "PH" },
  { code: "SGN", city: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN" },
  { code: "HAN", city: "Hanoi", country: "Vietnam", countryCode: "VN" },
  { code: "DAD", city: "Da Nang", country: "Vietnam", countryCode: "VN" },
  { code: "CXR", city: "Nha Trang", country: "Vietnam", countryCode: "VN" },
  { code: "PQC", city: "Phu Quoc", country: "Vietnam", countryCode: "VN" },
  { code: "HUI", city: "Hue", country: "Vietnam", countryCode: "VN" },
  { code: "HPH", city: "Hai Phong", country: "Vietnam", countryCode: "VN" },
  { code: "VDO", city: "Van Don", country: "Vietnam", countryCode: "VN" },
  { code: "RGN", city: "Yangon", country: "Myanmar", countryCode: "MM" },
  { code: "MDL", city: "Mandalay", country: "Myanmar", countryCode: "MM" },
  { code: "PNH", city: "Phnom Penh", country: "Cambodia", countryCode: "KH" },
  { code: "REP", city: "Siem Reap", country: "Cambodia", countryCode: "KH" },
  { code: "KTI", city: "Kratie", country: "Cambodia", countryCode: "KH" },
  { code: "VTE", city: "Vientiane", country: "Laos", countryCode: "LA" },
  { code: "LPQ", city: "Luang Prabang", country: "Laos", countryCode: "LA" },
  { code: "BWN", city: "Bandar Seri Begawan", country: "Brunei", countryCode: "BN" },
  { code: "DIL", city: "Dili", country: "Timor-Leste", countryCode: "TL" },

  // ===== CENTRAL ASIA (mapped to Middle East) =====
  { code: "TSE", city: "Astana", country: "Kazakhstan", countryCode: "KZ" },
  { code: "ALA", city: "Almaty", country: "Kazakhstan", countryCode: "KZ" },
  { code: "TAS", city: "Tashkent", country: "Uzbekistan", countryCode: "UZ" },
  { code: "SKD", city: "Samarkand", country: "Uzbekistan", countryCode: "UZ" },
  { code: "FRU", city: "Bishkek", country: "Kyrgyzstan", countryCode: "KG" },
  { code: "DYU", city: "Dushanbe", country: "Tajikistan", countryCode: "TJ" },
  { code: "ASB", city: "Ashgabat", country: "Turkmenistan", countryCode: "TM" },

  // ===== PACIFIC ISLANDS (mapped to Australia/NZ) =====
  { code: "APW", city: "Apia", country: "Samoa", countryCode: "WS" },
  { code: "TBU", city: "Tongatapu", country: "Tonga", countryCode: "TO" },
  { code: "SUV", city: "Suva", country: "Fiji", countryCode: "FJ" },
  { code: "NOU", city: "Noumea", country: "New Caledonia", countryCode: "NC" },
  { code: "VLI", city: "Port Vila", country: "Vanuatu", countryCode: "VU" },
  { code: "HIR", city: "Honiara", country: "Solomon Islands", countryCode: "SB" },
  { code: "POM", city: "Port Moresby", country: "Papua New Guinea", countryCode: "PG" },
];

// Country code → region mapping
export const countryToRegion: Record<string, string> = {
  // Australia / New Zealand
  AU: "Australia / New Zealand",
  NZ: "Australia / New Zealand",
  FJ: "Australia / New Zealand",
  PF: "Australia / New Zealand",
  WS: "Australia / New Zealand",
  TO: "Australia / New Zealand",
  NC: "Australia / New Zealand",
  VU: "Australia / New Zealand",
  SB: "Australia / New Zealand",
  PG: "Australia / New Zealand",

  // Orient
  CN: "Orient",
  HK: "Orient",
  MO: "Orient",
  TW: "Orient",
  KR: "Orient",
  MN: "Orient",

  // Japan
  JP: "Japan",

  // North America (includes Central & South America, Caribbean)
  US: "North America",
  CA: "North America",
  MX: "North America",
  BR: "North America",
  AR: "North America",
  CL: "North America",
  PE: "North America",
  CO: "North America",
  EC: "North America",
  VE: "North America",
  UY: "North America",
  PY: "North America",
  BO: "North America",
  PA: "North America",
  CR: "North America",
  SV: "North America",
  GT: "North America",
  HN: "North America",
  NI: "North America",
  BZ: "North America",
  CU: "North America",
  DO: "North America",
  PR: "North America",
  JM: "North America",
  BS: "North America",
  TT: "North America",
  BB: "North America",
  AW: "North America",
  CW: "North America",

  // Europe
  GB: "Europe",
  FR: "Europe",
  DE: "Europe",
  NL: "Europe",
  ES: "Europe",
  IT: "Europe",
  PT: "Europe",
  CH: "Europe",
  AT: "Europe",
  BE: "Europe",
  LU: "Europe",
  IE: "Europe",
  DK: "Europe",
  NO: "Europe",
  SE: "Europe",
  FI: "Europe",
  IS: "Europe",
  GR: "Europe",
  TR: "Europe",
  PL: "Europe",
  CZ: "Europe",
  HU: "Europe",
  RO: "Europe",
  BG: "Europe",
  RS: "Europe",
  HR: "Europe",
  SI: "Europe",
  MK: "Europe",
  AL: "Europe",
  SK: "Europe",
  EE: "Europe",
  LV: "Europe",
  LT: "Europe",
  UA: "Europe",
  RU: "Europe",
  GE: "Europe",
  AM: "Europe",
  AZ: "Europe",
  MT: "Europe",
  CY: "Europe",

  // Middle East
  AE: "Middle East",
  QA: "Middle East",
  SA: "Middle East",
  BH: "Middle East",
  KW: "Middle East",
  OM: "Middle East",
  JO: "Middle East",
  LB: "Middle East",
  IL: "Middle East",
  EG: "Middle East",
  DZ: "Middle East",
  MA: "Middle East",
  TN: "Middle East",
  LY: "Middle East",
  IQ: "Middle East",
  IR: "Middle East",
  SD: "Middle East",
  ET: "Middle East",
  KZ: "Middle East",
  UZ: "Middle East",
  KG: "Middle East",
  TJ: "Middle East",
  TM: "Middle East",

  // South Africa
  ZA: "South Africa",
  KE: "South Africa",
  NG: "South Africa",
  GH: "South Africa",
  TZ: "South Africa",
  UG: "South Africa",
  MZ: "South Africa",
  MW: "South Africa",
  ZW: "South Africa",
  ZM: "South Africa",
  BW: "South Africa",
  NA: "South Africa",
  MU: "South Africa",
  MG: "South Africa",
  SC: "South Africa",
  SN: "South Africa",
  CI: "South Africa",
  LR: "South Africa",
  CM: "South Africa",
  CD: "South Africa",
  CG: "South Africa",
  GA: "South Africa",
  RE: "South Africa",
  RW: "South Africa",

  // South Asia
  IN: "South Asia",
  PK: "South Asia",
  BD: "South Asia",
  LK: "South Asia",
  MV: "South Asia",
  NP: "South Asia",
  BT: "South Asia",

  // Southeast Asia
  SG: "Southeast Asia",
  MY: "Southeast Asia",
  TH: "Southeast Asia",
  ID: "Southeast Asia",
  PH: "Southeast Asia",
  VN: "Southeast Asia",
  MM: "Southeast Asia",
  KH: "Southeast Asia",
  LA: "Southeast Asia",
  BN: "Southeast Asia",
  TL: "Southeast Asia",
};

export function getRegionForAirport(code: string): string | null {
  const airport = airports.find((a) => a.code === code);
  if (!airport) return null;
  return countryToRegion[airport.countryCode] || null;
}

export function getAirportByCode(code: string): Airport | undefined {
  return airports.find((a) => a.code === code.toUpperCase());
}

export function searchAirports(query: string): Airport[] {
  const q = query.toUpperCase().trim();
  if (!q) return [];
  return airports
    .filter(
      (a) =>
        a.code.includes(q) ||
        a.city.toUpperCase().includes(q) ||
        a.country.toUpperCase().includes(q)
    )
    .slice(0, 15);
}