const airports = [
  // ===== AUSTRALIA / NEW ZEALAND =====
  { code: "SYD", city: "Sydney", country: "Australia", countryCode: "AU" },
  { code: "MEL", city: "Melbourne", country: "Australia", countryCode: "AU" },
  { code: "BNE", city: "Brisbane", country: "Australia", countryCode: "AU" },
  { code: "PER", city: "Perth", country: "Australia", countryCode: "AU" },
  { code: "ADL", city: "Adelaide", country: "Australia", countryCode: "AU" },
  { code: "CBR", city: "Canberra", country: "Australia", countryCode: "AU" },
  { code: "OOL", city: "Gold Coast", country: "Australia", countryCode: "AU" },
  { code: "CNS", city: "Cairns", country: "Australia", countryCode: "AU" },
  { code: "HBA", city: "Hobart", country: "Australia", countryCode: "AU" },
  { code: "DRW", city: "Darwin", country: "Australia", countryCode: "AU" },
  { code: "TSV", city: "Townsville", country: "Australia", countryCode: "AU" },
  { code: "ASP", city: "Alice Springs", country: "Australia", countryCode: "AU" },
  { code: "LST", city: "Launceston", country: "Australia", countryCode: "AU" },
  { code: "MCY", city: "Sunshine Coast", country: "Australia", countryCode: "AU" },
  { code: "NTL", city: "Newcastle", country: "Australia", countryCode: "AU" },
  { code: "AKL", city: "Auckland", country: "New Zealand", countryCode: "NZ" },
  { code: "CHC", city: "Christchurch", country: "New Zealand", countryCode: "NZ" },
  { code: "WLG", city: "Wellington", country: "New Zealand", countryCode: "NZ" },
  { code: "ZQN", city: "Queenstown", country: "New Zealand", countryCode: "NZ" },
  { code: "DUD", city: "Dunedin", country: "New Zealand", countryCode: "NZ" },
  { code: "PMR", city: "Palmerston North", country: "New Zealand", countryCode: "NZ" },
  { code: "NPE", city: "Napier", country: "New Zealand", countryCode: "NZ" },
  { code: "HLZ", city: "Hamilton", country: "New Zealand", countryCode: "NZ" },
  { code: "TRG", city: "Tauranga", country: "New Zealand", countryCode: "NZ" },
  { code: "ROT", city: "Rotorua", country: "New Zealand", countryCode: "NZ" },

  // ===== ORIENT (China, Taiwan, Hong Kong, Macau, Mongolia, South Korea) =====
  { code: "PEK", city: "Beijing", country: "China", countryCode: "CN" },
  { code: "PKX", city: "Beijing Daxing", country: "China", countryCode: "CN" },
  { code: "PVG", city: "Shanghai Pudong", country: "China", countryCode: "CN" },
  { code: "SHA", city: "Shanghai Hongqiao", country: "China", countryCode: "CN" },
  { code: "CAN", city: "Guangzhou", country: "China", countryCode: "CN" },
  { code: "SZX", city: "Shenzhen", country: "China", countryCode: "CN" },
  { code: "CTU", city: "Chengdu", country: "China", countryCode: "CN" },
  { code: "TFU", city: "Chengdu Tianfu", country: "China", countryCode: "CN" },
  { code: "CKG", city: "Chongqing", country: "China", countryCode: "CN" },
  { code: "KMG", city: "Kunming", country: "China", countryCode: "CN" },
  { code: "XIY", city: "Xi'an", country: "China", countryCode: "CN" },
  { code: "HGH", city: "Hangzhou", country: "China", countryCode: "CN" },
  { code: "NKG", city: "Nanjing", country: "China", countryCode: "CN" },
  { code: "WUH", city: "Wuhan", country: "China", countryCode: "CN" },
  { code: "CSX", city: "Changsha", country: "China", countryCode: "CN" },
  { code: "TSN", city: "Tianjin", country: "China", countryCode: "CN" },
  { code: "DLC", city: "Dalian", country: "China", countryCode: "CN" },
  { code: "SHE", city: "Shenyang", country: "China", countryCode: "CN" },
  { code: "TAO", city: "Qingdao", country: "China", countryCode: "CN" },
  { code: "XMN", city: "Xiamen", country: "China", countryCode: "CN" },
  { code: "HRB", city: "Harbin", country: "China", countryCode: "CN" },
  { code: "FOC", city: "Fuzhou", country: "China", countryCode: "CN" },
  { code: "ZUH", city: "Zhuhai", country: "China", countryCode: "CN" },
  { code: "NNG", city: "Nanning", country: "China", countryCode: "CN" },
  { code: "CGO", city: "Zhengzhou", country: "China", countryCode: "CN" },
  { code: "TNA", city: "Jinan", country: "China", countryCode: "CN" },
  { code: "SYX", city: "Sanya", country: "China", countryCode: "CN" },
  { code: "HAK", city: "Haikou", country: "China", countryCode: "CN" },
  { code: "URC", city: "Urumqi", country: "China", countryCode: "CN" },
  { code: "LHW", city: "Lanzhou", country: "China", countryCode: "CN" },
  { code: "HET", city: "Hohhot", country: "China", countryCode: "CN" },
  { code: "INC", city: "Yinchuan", country: "China", countryCode: "CN" },
  { code: "XNN", city: "Xining", country: "China", countryCode: "CN" },
  { code: "KWE", city: "Guiyang", country: "China", countryCode: "CN" },
  { code: "WNZ", city: "Wenzhou", country: "China", countryCode: "CN" },
  { code: "SWA", city: "Shantou", country: "China", countryCode: "CN" },
  { code: "NGB", city: "Ningbo", country: "China", countryCode: "CN" },
  { code: "TYN", city: "Taiyuan", country: "China", countryCode: "CN" },
  { code: "CGQ", city: "Changchun", country: "China", countryCode: "CN" },
  { code: "KHN", city: "Nanchang", country: "China", countryCode: "CN" },
  { code: "HFE", city: "Hefei", country: "China", countryCode: "CN" },
  { code: "LXA", city: "Lhasa", country: "China", countryCode: "CN" },
  { code: "HKG", city: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
  { code: "MFM", city: "Macau", country: "Macau", countryCode: "MO" },
  { code: "TPE", city: "Taipei Taoyuan", country: "Taiwan", countryCode: "TW" },
  { code: "TSA", city: "Taipei Songshan", country: "Taiwan", countryCode: "TW" },
  { code: "KHH", city: "Kaohsiung", country: "Taiwan", countryCode: "TW" },
  { code: "RMQ", city: "Taichung", country: "Taiwan", countryCode: "TW" },
  { code: "ICN", city: "Seoul Incheon", country: "South Korea", countryCode: "KR" },
  { code: "GMP", city: "Seoul Gimpo", country: "South Korea", countryCode: "KR" },
  { code: "PUS", city: "Busan", country: "South Korea", countryCode: "KR" },
  { code: "CJU", city: "Jeju", country: "South Korea", countryCode: "KR" },
  { code: "TAE", city: "Daegu", country: "South Korea", countryCode: "KR" },
  { code: "CJJ", city: "Cheongju", country: "South Korea", countryCode: "KR" },
  { code: "KWJ", city: "Gwangju", country: "South Korea", countryCode: "KR" },
  { code: "ULN", city: "Ulaanbaatar", country: "Mongolia", countryCode: "MN" },

  // ===== JAPAN =====
  { code: "NRT", city: "Tokyo Narita", country: "Japan", countryCode: "JP" },
  { code: "HND", city: "Tokyo Haneda", country: "Japan", countryCode: "JP" },
  { code: "KIX", city: "Osaka Kansai", country: "Japan", countryCode: "JP" },
  { code: "ITM", city: "Osaka Itami", country: "Japan", countryCode: "JP" },
  { code: "NGO", city: "Nagoya Chubu", country: "Japan", countryCode: "JP" },
  { code: "FUK", city: "Fukuoka", country: "Japan", countryCode: "JP" },
  { code: "CTS", city: "Sapporo Chitose", country: "Japan", countryCode: "JP" },
  { code: "OKA", city: "Okinawa Naha", country: "Japan", countryCode: "JP" },
  { code: "KOJ", city: "Kagoshima", country: "Japan", countryCode: "JP" },
  { code: "SDJ", city: "Sendai", country: "Japan", countryCode: "JP" },
  { code: "HIJ", city: "Hiroshima", country: "Japan", countryCode: "JP" },
  { code: "KMJ", city: "Kumamoto", country: "Japan", countryCode: "JP" },
  { code: "NGS", city: "Nagasaki", country: "Japan", countryCode: "JP" },
  { code: "OIT", city: "Oita", country: "Japan", countryCode: "JP" },
  { code: "TAK", city: "Takamatsu", country: "Japan", countryCode: "JP" },
  { code: "MYJ", city: "Matsuyama", country: "Japan", countryCode: "JP" },
  { code: "KMQ", city: "Komatsu", country: "Japan", countryCode: "JP" },
  { code: "AOJ", city: "Aomori", country: "Japan", countryCode: "JP" },
  { code: "AKJ", city: "Asahikawa", country: "Japan", countryCode: "JP" },
  { code: "KCZ", city: "Kochi", country: "Japan", countryCode: "JP" },

  // ===== NORTH AMERICA =====
  { code: "JFK", city: "New York JFK", country: "United States", countryCode: "US" },
  { code: "LAX", city: "Los Angeles", country: "United States", countryCode: "US" },
  { code: "ORD", city: "Chicago O'Hare", country: "United States", countryCode: "US" },
  { code: "ATL", city: "Atlanta", country: "United States", countryCode: "US" },
  { code: "DFW", city: "Dallas Fort Worth", country: "United States", countryCode: "US" },
  { code: "DEN", city: "Denver", country: "United States", countryCode: "US" },
  { code: "SFO", city: "San Francisco", country: "United States", countryCode: "US" },
  { code: "SEA", city: "Seattle", country: "United States", countryCode: "US" },
  { code: "LAS", city: "Las Vegas", country: "United States", countryCode: "US" },
  { code: "MIA", city: "Miami", country: "United States", countryCode: "US" },
  { code: "MCO", city: "Orlando", country: "United States", countryCode: "US" },
  { code: "EWR", city: "Newark", country: "United States", countryCode: "US" },
  { code: "BOS", city: "Boston", country: "United States", countryCode: "US" },
  { code: "MSP", city: "Minneapolis", country: "United States", countryCode: "US" },
  { code: "DTW", city: "Detroit", country: "United States", countryCode: "US" },
  { code: "PHL", city: "Philadelphia", country: "United States", countryCode: "US" },
  { code: "CLT", city: "Charlotte", country: "United States", countryCode: "US" },
  { code: "PHX", city: "Phoenix", country: "United States", countryCode: "US" },
  { code: "IAH", city: "Houston", country: "United States", countryCode: "US" },
  { code: "IAD", city: "Washington Dulles", country: "United States", countryCode: "US" },
  { code: "SAN", city: "San Diego", country: "United States", countryCode: "US" },
  { code: "SLC", city: "Salt Lake City", country: "United States", countryCode: "US" },
  { code: "YYZ", city: "Toronto Pearson", country: "Canada", countryCode: "CA" },
  { code: "YVR", city: "Vancouver", country: "Canada", countryCode: "CA" },
  { code: "YUL", city: "Montreal", country: "Canada", countryCode: "CA" },
  { code: "MEX", city: "Mexico City", country: "Mexico", countryCode: "MX" },
  { code: "GRU", city: "Sao Paulo Guarulhos", country: "Brazil", countryCode: "BR" },
  { code: "EZE", city: "Buenos Aires Ezeiza", country: "Argentina", countryCode: "AR" },

  // ===== EUROPE =====
  { code: "LHR", city: "London Heathrow", country: "United Kingdom", countryCode: "GB" },
  { code: "LGW", city: "London Gatwick", country: "United Kingdom", countryCode: "GB" },
  { code: "MAN", city: "Manchester", country: "United Kingdom", countryCode: "GB" },
  { code: "CDG", city: "Paris Charles de Gaulle", country: "France", countryCode: "FR" },
  { code: "FRA", city: "Frankfurt", country: "Germany", countryCode: "DE" },
  { code: "MUC", city: "Munich", country: "Germany", countryCode: "DE" },
  { code: "AMS", city: "Amsterdam Schiphol", country: "Netherlands", countryCode: "NL" },
  { code: "MAD", city: "Madrid Barajas", country: "Spain", countryCode: "ES" },
  { code: "BCN", city: "Barcelona", country: "Spain", countryCode: "ES" },
  { code: "FCO", city: "Rome Fiumicino", country: "Italy", countryCode: "IT" },
  { code: "MXP", city: "Milan Malpensa", country: "Italy", countryCode: "IT" },
  { code: "ZRH", city: "Zurich", country: "Switzerland", countryCode: "CH" },
  { code: "VIE", city: "Vienna", country: "Austria", countryCode: "AT" },
  { code: "BRU", city: "Brussels", country: "Belgium", countryCode: "BE" },
  { code: "CPH", city: "Copenhagen", country: "Denmark", countryCode: "DK" },
  { code: "ARN", city: "Stockholm Arlanda", country: "Sweden", countryCode: "SE" },
  { code: "OSL", city: "Oslo Gardermoen", country: "Norway", countryCode: "NO" },
  { code: "HEL", city: "Helsinki", country: "Finland", countryCode: "FI" },
  { code: "ATH", city: "Athens", country: "Greece", countryCode: "GR" },
  { code: "IST", city: "Istanbul", country: "Turkey", countryCode: "TR" },
  { code: "DUB", city: "Dublin", country: "Ireland", countryCode: "IE" },
  { code: "WAW", city: "Warsaw Chopin", country: "Poland", countryCode: "PL" },

  // ===== MIDDLE EAST =====
  { code: "DXB", city: "Dubai", country: "United Arab Emirates", countryCode: "AE" },
  { code: "AUH", city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE" },
  { code: "DOH", city: "Doha Hamad", country: "Qatar", countryCode: "QA" },
  { code: "RUH", city: "Riyadh", country: "Saudi Arabia", countryCode: "SA" },
  { code: "JED", city: "Jeddah", country: "Saudi Arabia", countryCode: "SA" },
  { code: "BAH", city: "Bahrain", country: "Bahrain", countryCode: "BH" },
  { code: "KWI", city: "Kuwait", country: "Kuwait", countryCode: "KW" },
  { code: "MCT", city: "Muscat", country: "Oman", countryCode: "OM" },

  // ===== SOUTH AFRICA =====
  { code: "JNB", city: "Johannesburg", country: "South Africa", countryCode: "ZA" },
  { code: "CPT", city: "Cape Town", country: "South Africa", countryCode: "ZA" },
  { code: "DUR", city: "Durban", country: "South Africa", countryCode: "ZA" },

  // ===== SOUTH ASIA =====
  { code: "DEL", city: "Delhi", country: "India", countryCode: "IN" },
  { code: "BOM", city: "Mumbai", country: "India", countryCode: "IN" },
  { code: "BLR", city: "Bengaluru", country: "India", countryCode: "IN" },
  { code: "MAA", city: "Chennai", country: "India", countryCode: "IN" },
  { code: "CCU", city: "Kolkata", country: "India", countryCode: "IN" },
  { code: "HYD", city: "Hyderabad", country: "India", countryCode: "IN" },
  { code: "COK", city: "Kochi", country: "India", countryCode: "IN" },
  { code: "AMD", city: "Ahmedabad", country: "India", countryCode: "IN" },
  { code: "DAC", city: "Dhaka", country: "Bangladesh", countryCode: "BD" },
  { code: "CMB", city: "Colombo", country: "Sri Lanka", countryCode: "LK" },
  { code: "MLE", city: "Male", country: "Maldives", countryCode: "MV" },

  // ===== SOUTHEAST ASIA =====
  { code: "SIN", city: "Singapore Changi", country: "Singapore", countryCode: "SG" },
  { code: "KUL", city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
  { code: "PEN", city: "Penang", country: "Malaysia", countryCode: "MY" },
  { code: "BKK", city: "Bangkok Suvarnabhumi", country: "Thailand", countryCode: "TH" },
  { code: "HKT", city: "Phuket", country: "Thailand", countryCode: "TH" },
  { code: "CGK", city: "Jakarta Soekarno-Hatta", country: "Indonesia", countryCode: "ID" },
  { code: "DPS", city: "Bali Ngurah Rai", country: "Indonesia", countryCode: "ID" },
  { code: "SUB", city: "Surabaya", country: "Indonesia", countryCode: "ID" },
  { code: "KNO", city: "Medan Kualanamu", country: "Indonesia", countryCode: "ID" },
  { code: "MNL", city: "Manila", country: "Philippines", countryCode: "PH" },
  { code: "CEB", city: "Cebu", country: "Philippines", countryCode: "PH" },
  { code: "SGN", city: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN" },
  { code: "HAN", city: "Hanoi", country: "Vietnam", countryCode: "VN" },
  { code: "DAD", city: "Da Nang", country: "Vietnam", countryCode: "VN" },
  { code: "RGN", city: "Yangon", country: "Myanmar", countryCode: "MM" },
  { code: "PNH", city: "Phnom Penh", country: "Cambodia", countryCode: "KH" },
];

const countryToRegion = {
  AU: "Australia / New Zealand", NZ: "Australia / New Zealand",
  CN: "Orient", HK: "Orient", MO: "Orient", TW: "Orient", KR: "Orient", MN: "Orient",
  JP: "Japan",
  US: "North America", CA: "North America", MX: "North America", BR: "North America", AR: "North America",
  GB: "Europe", FR: "Europe", DE: "Europe", NL: "Europe", ES: "Europe", IT: "Europe", CH: "Europe", AT: "Europe", BE: "Europe", DK: "Europe", SE: "Europe", NO: "Europe", FI: "Europe", GR: "Europe", TR: "Europe", IE: "Europe", PL: "Europe",
  AE: "Middle East", QA: "Middle East", SA: "Middle East", BH: "Middle East", KW: "Middle East", OM: "Middle East",
  ZA: "South Africa",
  IN: "South Asia", BD: "South Asia", LK: "South Asia", MV: "South Asia",
  SG: "Southeast Asia", MY: "Southeast Asia", TH: "Southeast Asia", ID: "Southeast Asia", PH: "Southeast Asia", VN: "Southeast Asia", MM: "Southeast Asia", KH: "Southeast Asia"
};
